### PR TITLE
ros2_object_analytics: 0.5.2-0 in 'crystal/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by yechun1**
Increasing version of package(s) in repository `ros2_object_analytics` to `0.5.2-0`:

- upstream repository: https://github.com/intel/ros2_object_analytics.git
- release repository: https://github.com/ros2-gbp/ros2_object_analytics-release.git
- distro file: `crystal/distribution.yaml`
- bloom version: `0.6.9`
- previous version for package: `0.5.1-0`

## object_analytics_msgs

```
* Merge remote-tracking branch 'origin/master' into crystal
* Contributors: Chris Ye
```

## object_analytics_node

```
* rename launcher filename
* add ament_cmake_gtest in package.xml
* Merge remote-tracking branch 'origin/master' into crystal
* Disable tracking for CRYSTAL RELEASE
* Contributors: Chris Ye
```

## object_analytics_rviz

```
* Merge remote-tracking branch 'origin/master' into crystal
* Contributors: Chris Ye
```

### CODE REVIEW

**Comment by yechun1** [comment]
fixed buildfarm build issue

**Comment by nuclearsandwich** [comment]
@yechun1 this PR is failing checks because the source branch `crystal` doesn't currently exist.

Most packages in ROS 2 stay with a `master` or `latest` branch until there is a need to introduce breaking changes targeting a future ROS 2 release. At which point a branch named for the previous rosdistro (i.e. `bouncy`) is created so that bugfixes and compatible changes can still be applied.
This is different from ROS 1, where the common convention is for a `*-devel` branch named for the earliest rosdistro the branch still supports.

You may use either a `master` or `crystal` branch for this package but the source entry in the distribution.yaml and the repository need to agree.

**Comment by yechun1** [comment]
@nuclearsandwich 
We have changed crystal branch to master branch for easily bloom release with version number bump. Sorry that we forget to change the src version, we have resubmitted the PR and change the crystal branch to master branch, hope 0.5.2 could pass CI and buildfarm build.

**Comment by dirk-thomas** [comment]
You should have received a notification email from Jenkins about the following warning: http://build.ros2.org/view/Cdev/job/Cdev__ros2_object_analytics__ubuntu_bionic_amd64/6/warnings24Result/ When you have a chance please fix it in the source repo (which will trigger a new devel build) - no need to create a new release with the patch though.

**Comment by yechun1** [comment]
OK. We'll fix on these.

**Pull request merged**
