### PR TITLE
Release cartographer 2.0.0.

### PR DESCRIPTION
**Pull request by nuclearsandwich**

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]
This seems strange to me, since we don't own cartographer, I would have thought we would have just used the commit hash, but w/e.

**Comment by nuclearsandwich** [comment]
cc @mikaelarguedas @clalancette was it intended to bump cartographer for this release (as opposed to cartographer_ros for example)?

**Comment by mikaelarguedas** [comment]
Yeah I'm not convinced either but from what I understood from @clalancette all the packages he forked and is maintaining are to be bumped to 2.0.0

**Comment by nuclearsandwich** [comment]
I'm going to assume this is on the level. We can always retract it if this is a mistake.

**Pull request merged**
