### PR TITLE
Don't release rviz-rendering-tests

### PR DESCRIPTION
**Pull request by mikaelarguedas**
@wjwwood not sure if the release of this was intentional or not. Can you confirm/infirm ?

Opening this so that we can keep in mind for the upcoming patch release if we don't want to release it

### CODE REVIEW

**Comment by wjwwood** [comment]
Yeah, I thought @nuclearsandwich asked me about that, but it might have gotten over looked. No need to release that package though.

**Review by tfoote — APPROVED** [review]
note that we should add it to the bloom ignores in the release repository too.

**Comment by mikaelarguedas** [comment]
> note that we should add it to the bloom ignores in the release repository too.

:+1:

**Comment by nuclearsandwich** [comment]
> I thought @nuclearsandwich asked me about that, but it might have gotten over looked. No need to release that package though.



> note that we should add it to the bloom ignores in the release repository too.

Yeah I think this was on my list to ignore but at the late hour (or early depending on where you're counting from) I forgot to set the bloom ignore.

**Comment by dirk-thomas** [comment]
I would suggest to add the package name to the ignore file now rather than waiting for the next release and having to remember this.

**Comment by nuclearsandwich** [comment]
> I would suggest to add the package name to the ignore file now rather than waiting for the next release and having to remember this.

https://github.com/ros2-gbp/rviz-release/pull/1

**Comment by mikaelarguedas** [comment]
Thanks @nuclearsandwich, feel free to merge both PRs when you see fit

**Pull request merged**
