### PR TITLE
apriltag: 0.9.8-0 in 'bouncy/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by christianrauch**
Increasing version of package(s) in repository `apriltag` to `0.9.8-0`:

- upstream repository: https://github.com/christianrauch/apriltag2.git
- release repository: https://github.com/christianrauch/apriltag2-release.git
- distro file: `bouncy/distribution.yaml`
- bloom version: `0.6.7`
- previous version for package: `null`

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Thanks @christianrauch, for this to build successfully, the dependencies of the apriltag library need to be listed in the package.xml (e.g. for OpenCV you will need a dependency on [`libopencv-dev`](https://github.com/ros/rosdistro/blob/ef19c9dac99f1a4e2795c6bf93b14b908ba4925a/rosdep/base.yaml#L2423))

**Comment by christianrauch** [comment]
The opencv dependency is optional since it is only required to build the demo executable `opencv_demo` which is not used by ROS. I.e. it is only built if `OpenCV_FOUND`. OpenCV is not required for the core functionality of the library.

**Comment by mikaelarguedas** [comment]
oh my bad :) :+1:

**Comment by christianrauch** [comment]
The build fails, trying to install to a ridiculously long path: http://build.ros2.org/job/Bbin_uB64__apriltag__ubuntu_bionic_amd64__binary/1/console

There is some recursive appending of install paths going on. This did not happen on my local builds and it is not obvious for me from the `CMakeLists.txt`, why this might happen.
Is there a way I can test these bloom builds locally before pushing them to the build server?

Edit: The issue must be related to `${CMAKE_INSTALL_PREFIX}`. Removing it might solve the issue. Is bloom changing `CMAKE_INSTALL_PREFIX` in some recursive way?

**Comment by christianrauch** [comment]
@mikaelarguedas Do you have an idea why this recursive appending of `CMAKE_INSTALL_PREFIX` happens and how I can debug this locally without pushing to the build server?

**Comment by mikaelarguedas** [comment]
Buildfarm jobs can be ran locally by following the [documentation available on the `ros_buildfarm` repository](https://github.com/ros-infrastructure/ros_buildfarm/tree/master/doc). In this case the failine job is a "binary" / "release" job so this documentation should be the one:
https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/release_jobs.rst#run-the-release-job-locally

And the invocation should look similar to:
```
generate_release_script.py https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml bouncy default apriltag ubuntu bionic amd64 > /tmp/release_job/release_job_bouncy_apriltag.sh
cd /tmp/release_job/
sh release_job_bouncy_apriltag.sh
```

@nuclearsandwich FYI

**Comment by nuclearsandwich** [comment]
Self-assigning temporarily to remember to take a look at this as well.

**Comment by christianrauch** [comment]
Thanks. The local build produces the same issue.
However, changing the source before the build, to investigate this issue, is quite tricky since it involves changing the source deb and regenerating the *.dsc files.
Can I temporary use a local source directory for the local build?

Btw, should I open a new issue for in the buildfarm repo to track this issue?

**Pull request merged**
