### PR TITLE
navigation2: 0.1.2-0 in 'crystal/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by SteveMacenski**
Increasing version of package(s) in repository `navigation2` to `0.1.2-0`:

- upstream repository: https://github.com/ros-planning/navigation2.git
- release repository: https://github.com/SteveMacenski/navigation2-release.git
- distro file: `crystal/distribution.yaml`
- bloom version: `0.6.9`
- previous version for package: `null`

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@dirk-thomas no reason this time to expect it to not build.

**Comment by SteveMacenski** [comment]
I'm seeing the pr/dev builds fail with missing rosdep key `ros-crystal-builtin-interfaces` which seem to be in here [in ros2/rosdistro](https://github.com/ros2/rosdistro/blob/ros2/crystal/distribution.yaml#L730). The src build was successful. I'm seeing all the builtin interfaces jobs succeed recently but still failing here. Any thoughts? It looks like an issue upstream of me but just making sure before I sit in a holding pattern.  

```

15:22:28 Traceback (most recent call last):
15:22:28   File "/usr/lib/python3/dist-packages/apt/cache.py", line 257, in __getitem__
15:22:28     return self._weakref[key]
15:22:28   File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
15:22:28     o = self.data[key]()
15:22:28 KeyError: 'ros-crystal-builtin-interfaces'
15:22:28 
15:22:28 During handling of the above exception, another exception occurred:
15:22:28 
15:22:28 Traceback (most recent call last):
15:22:28   File "/usr/lib/python3/dist-packages/apt/cache.py", line 260, in __getitem__
15:22:28     rawpkg = self._cache[key]
15:22:28 KeyError: 'ros-crystal-builtin-interfaces'
15:22:28 
15:22:28 During handling of the above exception, another exception occurred:
15:22:28 
15:22:28 Traceback (most recent call last):
15:22:28   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 266, in <module>
15:22:28     main()
15:22:28   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 126, in main
15:22:28     get_binary_package_versions(apt_cache, debian_pkg_names))
15:22:28   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 144, in get_binary_package_versions
15:22:28     pkg = apt_cache[debian_pkg_name]
15:22:28   File "/usr/lib/python3/dist-packages/apt/cache.py", line 262, in __getitem__
15:22:28     raise KeyError('The cache has no package named %r' % key)
15:22:28 KeyError: "The cache has no package named 'ros-crystal-builtin-interfaces'"
15:22:28 Build step 'Execute shell' marked build as failure
```

**Comment by nuclearsandwich** [comment]
Hello @SteveMacenski some dependency hygiene issues in a recent release left many packages unable to build. So the farm has been blocked on those for a while. They're just coming up now so as packages repopulate builds should start turning over again.

**Comment by SteveMacenski** [comment]
Awesome, thanks. Just making sure there wasn't any action on my end I needed to do and end up missing the sync date. I'll just keep a watch

**Comment by nuclearsandwich** [comment]
@SteveMacenski I did notice that some builds have failures from earlier which appear to be related to dependencies missing from the package.xml manifest. I've started a PR to get those sorted out but it's far from exhaustive https://github.com/ros-planning/navigation2/pull/455

**Comment by SteveMacenski** [comment]
Got it, that's incredibly annoying. Thanks for the help, I will need to get on a call with those folks and figure out the rest.

**Pull request merged**
