### PR TITLE
Reference ardent version for source repo

### PR DESCRIPTION
**Pull request by dhood**
Looking for confirmation this is a reasonable thing to do before doing so for other repos.

Otherwise, for example, the version of `launch` on ros2index will reference the changelog off master which is incorrect.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Yeah that's fine.
As we dont run any dev job for Ardent it will not have any impact on the farm. But should allow people to get the right branch if they use tools like rosinstall_generator.

Note that this can only be applied to repos for which we created an ardent branch (so thid-party packages and upstream ROS 1 packages will not be able to get this change)

**Comment by dhood** [comment]
Ah cool thanks for the extra context about what this impacts. I'll update other repos where appropriate.

**Comment by dhood** [comment]
Other non-third-party/ROS 1 packages updated in ce0e65f6882fb948f39d44e7ab4e76fca4b21b01

**Comment by mikaelarguedas** [comment]
Can you please also update the third party packages that we forked ? (e.g. cartographer, cartographer_ros)

**Comment by dhood** [comment]
Done in https://github.com/ros2/rosdistro/pull/262/commits/da6d6e0bb01f1d064f349514fef593d6bf4b269d. For future reference, `urdfdom`, `urdfdom_headers`, `vision_msgs` were left as `ros2` since they don't have an `ardent` branch upstream.

**Comment by mikaelarguedas** [comment]
list of repos not using the ardent branch:
```
console_bridge
ecl_tools
fastcdr
fastrtps
osrf_pycommon
urdfdom
urdfdom_headers
vision_msgs
```

All are third party or forked repos that don't have an ardent branch :+1:

**Review by mikaelarguedas — APPROVED** [review]
lgtm

**Pull request merged**
