### PR TITLE
Remove gazebo_ros_pkgs from Bouncy

### PR DESCRIPTION
**Pull request by chapulina**
I'm not sure if this is allowed, is it?

This was added on https://github.com/ros2/rosdistro/pull/258 so we could get CI running, but Gazebo packages have never been released for Bouncy. Ever since, the code has diverged and we currently have no branch that works with Bouncy or plans to maintain one. I've already manually disabled the jobs, but it would be nice to remove this here too so users don't get the wrong impression that Gazebo should work with Bouncy.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
> I'm not sure if this is allowed, is it?

If the devel and PR jobs aren't providing useful results we can at least turn them both off. (By changing `test_pull_requests: true` to `test_commits: false`, PR jobs are off by default, devel jobs are on by default). If any of the gazebo_ros_pkgs worked in bouncy, I think it's worth leaving this here for those who would be using them. If not, I think we can yank it but I'll defer to the knowledge of @tfoote

**Comment by dirk-thomas** [comment]
The current branch doesn't even build: http://build.ros2.org/view/Bdev/job/Bdev__gazebo_ros_pkgs__ubuntu_bionic_amd64/19/

Two options:
* just merge this removing it from Bouncy
* create a Bouncy specific branch in the `gazebo_ros_pkgs` repo which does work with Bouncy and update this PR to use that new branch instead

**Comment by chapulina** [comment]
I'd prefer not to maintain a bouncy branch and only officially support `gazebo_ros_pkgs` from crystal onwards, but if there's demand, I can trace back what was the last commit that worked with bouncy.

**Comment by dirk-thomas** [comment]
> I'd prefer not to maintain a bouncy branch

Sounds good to me.

**Pull request merged**
