### PR TITLE
ecl_tools: 1.0.0-0 in 'bouncy/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by stonier**
Increasing version of package(s) in repository `ecl_tools` to `1.0.0-0`:

- upstream repository: https://github.com/stonier/ecl_tools.git
- release repository: https://github.com/yujinrobot-release/ecl_tools-release.git
- distro file: `bouncy/distribution.yaml`
- bloom version: `0.6.7`
- previous version for package: `null`

### CODE REVIEW

**Comment by stonier** [comment]
@mikaelarguedas I've found the build farm [here](http://build.ros2.org) but is there a page similar to http://repositories.ros.org/status_page/ros_melodic_default.html for `bouncy`?

These might be good breadcrumbs to add to https://github.com/ros2/ros2/wiki/Releasing-a-ROS-2-package-with-bloom.

**Comment by mikaelarguedas** [comment]
The ROS 2 Packages are currently hosted on repo.ros2.org, the status pages can be found [here](http://repo.ros2.org/status_page/).

> These might be good breadcrumbs to add to https://github.com/ros2/ros2/wiki/Releasing-a-ROS-2-package-with-bloom.

Sounds like a great idea :+1:
If you get a chance, could you submit that improvement to the wiki page directly?

**Comment by stonier** [comment]
Thanks, added!

**Comment by mikaelarguedas** [comment]
Thanks!

**Pull request merged**
