### PR TITLE
apriltag2_ros2: 1.0.0-0 in 'bouncy/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by christianrauch**
Increasing version of package(s) in repository `apriltag2_ros2` to `1.0.0-0`:

- upstream repository: https://github.com/christianrauch/apriltag2_ros2.git
- release repository: https://github.com/christianrauch/apriltag2_ros2-release.git
- distro file: `bouncy/distribution.yaml`
- bloom version: `0.6.6`
- previous version for package: `null`

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Thanks @christianrauch for releasing your packages into ROS 2.

Looking at the source and release repos, I'm afraid this release will have no effect:
- the source repository has a package.xml at the root but no CMakeLists associated with it
  - So bloom didnt identify any of the packages in it and this PR lists a single package `apriltag2_ros2` that doesn't have a CMakeLists.txt.
  - The buildfarm will not be able to build them and fail with a CMake Error like: 
```
CMake Error: The source directory "<WORKSPACE>/apriltag2_ros2"  does not appear to contain CMakeLists.txt
```

It looks like each of these packages have their own source repository. Could you release these repository 1 by 1 like you would do in ROS 1 ? this should result in 4 valid repository entries in the distribution file and the ability for the buildfarm to build them individually.

Thanks!

**Comment by christianrauch** [comment]
My intention with the `apriltag2_ros2` was to release all packages synchronised and have a meta package with these packages as a dependency.

I thought that since ROS2, colcon can build packages without a `CMakeLists.txt`. Would it help if I remove the `<buildtool_depend>ament_cmake</buildtool_depend>` from the `package.xml`? Alternatively, could I add a fake `CMakeLists.txt` that does not produce any output but only defines a project `apriltag2_ros2`?

**Comment by mikaelarguedas** [comment]
The infrastructure for releasing is the same for ROS 1 and ROS 2. The tools stops going down subdirectories as soon as they find a package.xml. So all your packages need to be "side-by-side".

If you want to provide a metapackage, you will need a sibling package in your repository, instead of a package.xml at the root of the repo (you can see [common_interfaces](https://github.com/ros2/common_interfaces) for an example of repository having packages and a metapackage).

Though as you already have repositories for each of these packages, I would recommend releasing them independently from the branch you use for ROS 2 development.

**Comment by christianrauch** [comment]
Thanks for going into the details. I missed that packages (i.e. `package.xml`) are not allowed to be nested.
I will close this for now and submit a new PR with the proper order.

**Pull request closed without merging**
