### PR TITLE
ecl_tools: 0.62.1-0 in 'ardent/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by stonier**
Increasing version of package(s) in repository `ecl_tools` to `0.62.1-0`:

- upstream repository: https://github.com/stonier/ecl_tools.git
- release repository: https://github.com/yujinrobot-release/ecl_tools-release.git
- distro file: `ardent/distribution.yaml`
- bloom version: `0.6.1`
- previous version for package: `null`

### CODE REVIEW

**Comment by stonier** [comment]
Wondering if it's too early to start submitting non-core packages to bloom for ros2?

Interested in road testing a path to py_trees / kobuki in simulation.

**Comment by mikaelarguedas** [comment]
We don't run the ROS 2 buildfarm continuously, only when rolling a set of debs for a patch release.
Ardent doesn't take third-party package submission but we are planning on doing so for the next release (Bouncy).

I'll defer to @dirk-thomas and @nuclearsandwich about "if something"/"what" can be done in the meantime for your use case.

**Comment by dirk-thomas** [comment]
We are happy to allow releasing packages into ROS 2. We are not "advertising" it currently though.

Please also keep in mind that this won't affect the "fat archives" we currently build for all platforms (Linux, macOS, Windows) but only result in Debian packages. This is due to the fact the fat archives are produces by a custom Jenkins instance (ci.ros2.org) which is not using `ros_buildfarm` (build.ros2.org).

Also the `doc` entry is not being used at this time (not sure if you want to keep it?).

Currently we also don't have any Travis CI on this repo. @nuclearsandwich Maybe we should port these tests from the upstream repo if we get more PRs in the future?

**Comment by nuclearsandwich** [comment]
> Maybe we should port these tests from the upstream repo if we get more PRs in the future?

This is already ticketed as #13 and is targeted to bouncy. Since I've done very little with Travis CI in the past, I'd enjoy the opportunity to get it set up but if someone feels a mighty need to get it wired up before I can schedule it, feel free.

**Comment by stonier** [comment]
Thanks for the background information @dirk-thomas. Was keen to kick into shape for windows & mac, but I'm fine with debs only until there's some good pre-release infrastructure around.

**Comment by stonier** [comment]
If it's only running nightly, it'll probably be important to have the pre-release infrastructure setup. I'm bound to have a swathe of problems to sort out initially. Is the pre-release infrastructure working for Ardent? If not, I'm fine waiting for it to land - plenty to do just getting the software working from sources.

**Comment by dirk-thomas** [comment]
> Is the pre-release infrastructure working for Ardent?

No, not at the moment. build.ros2.org only has `sourcedeb` and `binarydeb` jobs since they can be built by using `bloom` and calling out to `dpkg-buildpackage`. All other job types (`devel`, `pr`, `prerelease`) are not available since the `ros_buildfarm` repo uses `catkin_make_isolated` only.

We are hesitant to add conditional logic for `ament_tools` at this point since we don't want to maintain two separate build tools. Therefore this is blocked on our decision around which build tool to use in the future (for ROS 1 as well as ROS 2, and also for non_ROS packages like Gazebo with the ignition packages). We will hopefully have an update on this topic within a month. Especially for the next ROS 2 release in June we really need this infrastructure in place to let everyone test and release their packages.

**Comment by dirk-thomas** [comment]
@stonier Please let us know when you would like to sync built packages from `testing` to `main`. Since we don't do regular releases we don't have anyone check the status on a regular base.

**Comment by stonier** [comment]
Ok, I'll tentatively see how things go with the builds and how many issues I run into there. Thanks.

**Comment by mikaelarguedas** [comment]
@stonier I remember there was some effort in the community to get the ecl libraries ported to ROS 2. It may be of interest to you https://github.com/ros2/turtlebot2_demo/issues/76#issuecomment-354336401

**Comment by stonier** [comment]
Moving in this direction ... have sophus and ~90% of ecl converted to ament. Next step is to get them bloomed and then move onto the core c++ (non-ros) kobuki libraries. At that point the dependency graph back to ROS1 should mostly disappear.

**Comment by mikaelarguedas** [comment]
Great news!
I didn't mean to rush, but was rather hoping that there may be some code you could reuse from that other ticket to save you some porting time :)
But it looks like you got the porting part covered by now. Thanks!

**Comment by stonier** [comment]
Aye, the pull requests that came in were a good start, but these  had quite a few problems still lurking under the hood. Been resolving them and also working out how to switch to a CMake import/export target style since that simplifies the dependency variable management (more complex with ament since there is no longer the bundling of variables in `CATKIN_INCLUDE_DIRS` and company).

**Pull request merged**
