### PR TITLE
enable PR job for ament_lint

### PR DESCRIPTION
**Pull request by dirk-thomas**
To try if this works with an upcoming PR.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
From internal discussion, these are the questions to answer / act on before enabling PR jobs:

```
Need to update PRbuilder plugin
Set up tokens
Question: do we want to test PRs on ROS2 ? How does this play with bouncy?
How do webhooks work when 2 instances using same source repo?
```

As this will be discussed tomorrow I'd prefer holding this until then

**Comment by nuclearsandwich** [comment]
I've updated the Ghprb plugin and the associated GitHub API plugins and updated the token.

I think we also need to give the @ros-pull-request-builder user some permissions on the ros2 and ament orgs. Before we do so there are some implications I'd like to add to the discussion later today.

- [x] Need to update PRbuilder plugin
- [x] Set up tokens
- [x] Add ros-pull-request-builder to ROS 2 orgs (HOLD pending discussion)

**Comment by dirk-thomas** [comment]
Once this got reviewed (and the permissions have been added) I would like to get this merged to try one PR job on build.ros2.org.

**Comment by dirk-thomas** [comment]
We will accept the "increased risk" of giving owner permissions for the `ament` and `ros2` org units to @ros-pull-request-builder until the permissions for that user are being reduced to a non-owner role since we are doing the same for ROS 1 org units for many years already.

**Comment by dirk-thomas** [comment]
I will go ahead and merge this change in order to test a PR job on the `ament_lint` repo. This patch can be reverted afterwards if is that it undesired to keep it enabled.

**Comment by dirk-thomas** [comment]
Jenkins failed to configure the webhook for the `ament_lint` repo.

<details>
 <summary>An excerpt from the Jenkins log:</summary>

```
Jul 11, 2018 10:42:34 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger start
Starting the ghprb trigger for the Bpr__ament_lint__ubuntu_bionic_amd64 job; newInstance is true
Jul 11, 2018 10:42:34 AM INFO hudson.model.Run execute
Bdev_reconfigure-jobs #112 main build action completed: SUCCESS
Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth buildConnection
Unable to connect using credentials: 288c7562-16f1-4e2c-8a43-0ad353c64ed0
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.Requester.parse(Requester.java:617)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://api.github.com/user
	at org.kohsuke.github.Requester.parse(Requester.java:638)
	at org.kohsuke.github.Requester.parse(Requester.java:599)
	at org.kohsuke.github.Requester._to(Requester.java:277)
Caused: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:695)
	at org.kohsuke.github.Requester._to(Requester.java:298)
	at org.kohsuke.github.Requester.to(Requester.java:239)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:383)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:157)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:207)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.buildConnection(GhprbGitHubAuth.java:210)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.getConnection(GhprbGitHubAuth.java:219)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.getGitHub(GhprbTrigger.java:513)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:88)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:409)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.hookExist(GhprbRepository.java:274)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createHook(GhprbRepository.java:297)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger$StartHookRunnable.run(GhprbTrigger.java:1236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
No connection returned to GitHub server!
Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository getGitHubRepo
Unable to get repository [ ament/ament_lint ]
Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository createHook
Could not create web hook for repository ament/ament_lint. Does the user (from global configuration) have admin rights to the repository?
Jul 11, 2018 10:42:35 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger$StartHookRunnable run
Created hook for ament/ament_lint
```
</details>


@nuclearsandwich Can you clarify what token you have configure? The Jenkins config in the section "GitHub Pull Request Builder" seems to be different between build.ros.org and build.ros2.org.

**Comment by dirk-thomas** [comment]
Jenkins failed to configure the webhook for the `ament_lint` repo.

@nuclearsandwich Can you clarify what token you have configure? The Jenkins config in the section "GitHub Pull Request Builder" seems to be different between build.ros.org and build.ros2.org.

<details>
 <summary>An excerpt from the log:</summary>
```
Jul 11, 2018 10:42:34 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger start
Starting the ghprb trigger for the Bpr__ament_lint__ubuntu_bionic_amd64 job; newInstance is true
Jul 11, 2018 10:42:34 AM INFO hudson.model.Run execute
Bdev_reconfigure-jobs #112 main build action completed: SUCCESS
Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbGitHubAuth buildConnection
Unable to connect using credentials: 288c7562-16f1-4e2c-8a43-0ad353c64ed0
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.kohsuke.github.Requester.parse(Requester.java:617)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://api.github.com/user
	at org.kohsuke.github.Requester.parse(Requester.java:638)
	at org.kohsuke.github.Requester.parse(Requester.java:599)
	at org.kohsuke.github.Requester._to(Requester.java:277)
Caused: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:695)
	at org.kohsuke.github.Requester._to(Requester.java:298)
	at org.kohsuke.github.Requester.to(Requester.java:239)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:383)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:157)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:207)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.buildConnection(GhprbGitHubAuth.java:210)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.getConnection(GhprbGitHubAuth.java:219)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.getGitHub(GhprbTrigger.java:513)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:88)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.getGitHubRepo(GhprbRepository.java:409)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.hookExist(GhprbRepository.java:274)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createHook(GhprbRepository.java:297)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger$StartHookRunnable.run(GhprbTrigger.java:1236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository initGhRepository
No connection returned to GitHub server!
Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository getGitHubRepo
Unable to get repository [ ament/ament_lint ]
Jul 11, 2018 10:42:35 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRepository createHook
Could not create web hook for repository ament/ament_lint. Does the user (from global configuration) have admin rights to the repository?
Jul 11, 2018 10:42:35 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger$StartHookRunnable run
Created hook for ament/ament_lint
```
</details>

**Pull request merged**
