### PR TITLE
launch: 0.5.0-0 in 'bouncy/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by wjwwood**
Increasing version of package(s) in repository `launch` to `0.5.0-0`:

- upstream repository: https://github.com/ros2/launch.git
- release repository: https://github.com/ros2-gbp/launch-release.git
- distro file: `bouncy/distribution.yaml`
- bloom version: `0.6.4`
- previous version for package: `null`

## launch

```
* Fixed a bug where unclosed asyncio loops caused a traceback on the terminal on exit, but only in Python 3.5 (#85 <https://github.com/ros2/launch/issues/85>)
* Changed to use variable typing in comments to support python 3.5 (#81 <https://github.com/ros2/launch/issues/81>)
* New launch API (#74 <https://github.com/ros2/launch/issues/74>)
  * See pull request for more details and links to architecture documentation and the design doc.
* Moved launch source files into launch.legacy namespace (#73 <https://github.com/ros2/launch/issues/73>)
  * This was in preparation for the new launch API.
* [for launch.legacy] fixed a flake8 warning (#72 <https://github.com/ros2/launch/issues/72>)
* [for launch.legacy] set zip_safe to avoid warning during installation (#71 <https://github.com/ros2/launch/issues/71>)
* [for launch.legacy] Fix hang on keyboard interrupt (#69 <https://github.com/ros2/launch/issues/69>)
  * When keyboard interrupt exception occurs loop.run_forever is called. But there is no loop.stop call. This causes a hang.
* Contributors: Devin, Dirk Thomas, William Woodall, dhood
```

### CODE REVIEW

**Comment by dirk-thomas** [comment]
For the record: this wasn't ready to be released yet. The status page showed it to be ready since it doesn't declare a dependency on `lifecycle_msgs` which it needs.

**Comment by dhood** [comment]
maybe there's something off in the status page calculations because AFAICT it does have the dependency: https://github.com/ros2/launch/blob/035455758e09715abbda909b56fd7777444272f1/launch_ros/package.xml#L14

**Comment by wjwwood** [comment]
It's because I did a partial bloom release. `launch_ros` has this dependency, but I haven't released it yet.

**Comment by mikaelarguedas** [comment]
> maybe there's something off in the status page calculations because AFAICT it does have the dependency

I didnt verify how the status page does dependency calculation but I think it computes dependencies based on the ones declared for the previous release, not the current state of the default branch of the upstream repo

**Pull request merged**
