### PR TITLE
Release navigation 3.0.0-1

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Patch package.xml to work around upstream yaml-cpp issue.

https://github.com/ros2-gbp/navigation-release/blob/74c20adf07fc9c255881996d3dafdf07315b9d18/xenial/map_server/package.xml

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I am not sure why this issue is only cropping up now. But this should resolve it.

**Comment by nuclearsandwich** [comment]
@mikaelarguedas is standing right here and says if I merge I won't get in trouble.

**Comment by wjwwood** [comment]
Actually, is it because the `yaml-cpp` build dependency should be `yaml-cpp-dev` (or w/e is equivalent)?

**Comment by nuclearsandwich** [comment]
> Actually, is it because the yaml-cpp build dependency should be yaml-cpp-dev (or w/e is equivalent)?

The `yaml-cpp` key resolves to `libyaml-cpp-dev` on xenial: https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L4885

**Comment by wjwwood** [comment]
Ok, I guess not then. Must be the implicit dependency.

**Comment by nuclearsandwich** [comment]
🔵 http://build.ros2.org/view/Abin_uX64/job/Abin_uX64__map_server__ubuntu_xenial_amd64__binary/9/ the build is passing now!

**Pull request merged**
