### PR TITLE
rosbag2: 0.0.1-1 in 'crystal/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by Karsten1987**
Increasing version of package(s) in repository `rosbag2` to `0.0.1-1`:

- upstream repository: https://github.com/ros2/rosbag2.git
- release repository: https://github.com/ros2-gbp/rosbag2-release.git
- distro file: `crystal/distribution.yaml`
- bloom version: `0.6.9`
- previous version for package: `0.0.1-1`

## ros2bag

```
* Auto discovery of new topics (#63 <https://github.com/ros2/rosbag2/issues/63>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* Display bag summary using ros2 bag info (#45 <https://github.com/ros2/rosbag2/issues/45>)
* Use directory as bagfile and add additonal record options (#43 <https://github.com/ros2/rosbag2/issues/43>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* initial command line interface (#12 <https://github.com/ros2/rosbag2/issues/12>)
* (demo, sqlite3) First working rosbag2 implementation (#6 <https://github.com/ros2/rosbag2/issues/6>)
* initial setup
* Contributors: Alessandro Bottero, Andreas Greimel, Karsten Knese, Martin Idel
```

## rosbag2

```
* Split converters (#70 <https://github.com/ros2/rosbag2/issues/70>)
* GH-144 Add missing pop for warning pragma (#68 <https://github.com/ros2/rosbag2/issues/68>)
* Fix master build and small renamings (#67 <https://github.com/ros2/rosbag2/issues/67>)
* rename topic_with_types to topic_metadata
* use converter options
* GH-142 replace map with unordered map where possible (#65 <https://github.com/ros2/rosbag2/issues/65>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* Renaming struct members for consistency (#64 <https://github.com/ros2/rosbag2/issues/64>)
* Use converters when playing back files (#56 <https://github.com/ros2/rosbag2/issues/56>)
* Implement converter plugin for CDR format and add converter plugins package (#48 <https://github.com/ros2/rosbag2/issues/48>)
* Display bag summary using ros2 bag info (#45 <https://github.com/ros2/rosbag2/issues/45>)
* Add entry point for converter plugins (#47 <https://github.com/ros2/rosbag2/issues/47>)
* Extract recorder from rosbag2_transport, fix test naming (#44 <https://github.com/ros2/rosbag2/issues/44>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* Add correct timing behaviour for rosbag play (#32 <https://github.com/ros2/rosbag2/issues/32>)
* Improve sqlite usage and test stability (#31 <https://github.com/ros2/rosbag2/issues/31>)
* Record and play multiple topics (#27 <https://github.com/ros2/rosbag2/issues/27>)
* Allow an arbitrary topic to be recorded (#26 <https://github.com/ros2/rosbag2/issues/26>)
* Use serialized message directly (#24 <https://github.com/ros2/rosbag2/issues/24>)
* initial version of plugin based storage api (#7 <https://github.com/ros2/rosbag2/issues/7>)
* add visibility macro (#22 <https://github.com/ros2/rosbag2/issues/22>)
* (demo, sqlite3) First working rosbag2 implementation (#6 <https://github.com/ros2/rosbag2/issues/6>)
* initial setup
* Contributors: Alessandro Bottero, Andreas Greimel, Andreas Holzner, Karsten Knese, Martin Idel
```

## rosbag2_converter_default_plugins

```
* Split converters (#70 <https://github.com/ros2/rosbag2/issues/70>)
* Fix master build and small renamings (#67 <https://github.com/ros2/rosbag2/issues/67>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* Renaming struct members for consistency (#64 <https://github.com/ros2/rosbag2/issues/64>)
  * GH-118 Rename rosbag2_storage::TopicMetadata to TopicInformation and rosbag2_storage::TopicwithType to TopicMetadata
* Use converters when playing back files (#56 <https://github.com/ros2/rosbag2/issues/56>)
* Implement converter plugin for CDR format and add converter plugins package (#48 <https://github.com/ros2/rosbag2/issues/48>)
* Contributors: Alessandro Bottero, Andreas Holzner, Martin Idel
```

## rosbag2_storage

```
* rename topic_with_types to topic_metadata
* GH-142 replace map with unordered map where possible (#65 <https://github.com/ros2/rosbag2/issues/65>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* use uint8 for serialized message (#61 <https://github.com/ros2/rosbag2/issues/61>)
* Renaming struct members for consistency (#64 <https://github.com/ros2/rosbag2/issues/64>)
* Use converters when playing back files (#56 <https://github.com/ros2/rosbag2/issues/56>)
* Implement converter plugin for CDR format and add converter plugins package (#48 <https://github.com/ros2/rosbag2/issues/48>)
* Display bag summary using ros2 bag info (#45 <https://github.com/ros2/rosbag2/issues/45>)
* Use directory as bagfile and add additonal record options (#43 <https://github.com/ros2/rosbag2/issues/43>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* Add correct timing behaviour for rosbag play (#32 <https://github.com/ros2/rosbag2/issues/32>)
* Improve sqlite usage and test stability (#31 <https://github.com/ros2/rosbag2/issues/31>)
* Record and play multiple topics (#27 <https://github.com/ros2/rosbag2/issues/27>)
* Allow an arbitrary topic to be recorded (#26 <https://github.com/ros2/rosbag2/issues/26>)
* Use serialized message directly (#24 <https://github.com/ros2/rosbag2/issues/24>)
* initial version of plugin based storage api (#7 <https://github.com/ros2/rosbag2/issues/7>)
* (demo, sqlite3) First working rosbag2 implementation (#6 <https://github.com/ros2/rosbag2/issues/6>)
* initial setup
* Contributors: Alessandro Bottero, Andreas Greimel, Andreas Holzner, Karsten Knese, Martin Idel
```

## rosbag2_storage_default_plugins

```
* rename topic_with_types to topic_metadata
* GH-142 replace map with unordered map where possible (#65 <https://github.com/ros2/rosbag2/issues/65>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* use uint8 for serialized message (#61 <https://github.com/ros2/rosbag2/issues/61>)
* Renaming struct members for consistency (#64 <https://github.com/ros2/rosbag2/issues/64>)
* Display bag summary using ros2 bag info (#45 <https://github.com/ros2/rosbag2/issues/45>)
* Use directory as bagfile and add additonal record options (#43 <https://github.com/ros2/rosbag2/issues/43>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* Add correct timing behaviour for rosbag play (#32 <https://github.com/ros2/rosbag2/issues/32>)
* Improve sqlite iterator interface (#33 <https://github.com/ros2/rosbag2/issues/33>)
* Improve sqlite usage and test stability (#31 <https://github.com/ros2/rosbag2/issues/31>)
* Record all topics (#30 <https://github.com/ros2/rosbag2/issues/30>)
* Record and play multiple topics (#27 <https://github.com/ros2/rosbag2/issues/27>)
* Allow an arbitrary topic to be recorded (#26 <https://github.com/ros2/rosbag2/issues/26>)
* Use serialized message directly (#24 <https://github.com/ros2/rosbag2/issues/24>)
* add visibility macros (#28 <https://github.com/ros2/rosbag2/issues/28>)
* initial version of plugin based storage api (#7 <https://github.com/ros2/rosbag2/issues/7>)
* Contributors: Alessandro Bottero, Andreas Greimel, Andreas Holzner, Karsten Knese, Martin Idel
```

## rosbag2_test_common

```
* Auto discovery of new topics (#63 <https://github.com/ros2/rosbag2/issues/63>)
* GH-142 replace map with unordered map where possible (#65 <https://github.com/ros2/rosbag2/issues/65>)
* use uint8 for serialized message (#61 <https://github.com/ros2/rosbag2/issues/61>)
* Implement converter plugin for CDR format and add converter plugins package (#48 <https://github.com/ros2/rosbag2/issues/48>)
* Use directory as bagfile and add additonal record options (#43 <https://github.com/ros2/rosbag2/issues/43>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* Contributors: Alessandro Bottero, Andreas Greimel, Andreas Holzner, Karsten Knese, Martin Idel
```

## rosbag2_tests

```
* Auto discovery of new topics (#63 <https://github.com/ros2/rosbag2/issues/63>)
* Split converters (#70 <https://github.com/ros2/rosbag2/issues/70>)
* Fix master build and small renamings (#67 <https://github.com/ros2/rosbag2/issues/67>)
* rename topic_with_types to topic_metadata
* iterate_over_formatter
* GH-142 replace map with unordered map where possible (#65 <https://github.com/ros2/rosbag2/issues/65>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* Display bag summary using ros2 bag info (#45 <https://github.com/ros2/rosbag2/issues/45>)
* Use directory as bagfile and add additonal record options (#43 <https://github.com/ros2/rosbag2/issues/43>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* Contributors: Alessandro Bottero, Andreas Greimel, Andreas Holzner, Karsten Knese, Martin Idel
```

## rosbag2_transport

```
* Auto discovery of new topics (#63 <https://github.com/ros2/rosbag2/issues/63>)
* Fix master build and small renamings (#67 <https://github.com/ros2/rosbag2/issues/67>)
* rename topic_with_types to topic_metadata
* use converter options
* iterate_over_formatter
* GH-142 replace map with unordered map where possible (#65 <https://github.com/ros2/rosbag2/issues/65>)
* Use converters when recording a bag file (#57 <https://github.com/ros2/rosbag2/issues/57>)
* use uint8 for serialized message (#61 <https://github.com/ros2/rosbag2/issues/61>)
* Renaming struct members for consistency (#64 <https://github.com/ros2/rosbag2/issues/64>)
* Use converters when playing back files (#56 <https://github.com/ros2/rosbag2/issues/56>)
* Implement converter plugin for CDR format and add converter plugins package (#48 <https://github.com/ros2/rosbag2/issues/48>)
* Display bag summary using ros2 bag info (#45 <https://github.com/ros2/rosbag2/issues/45>)
* GH-117 Check also for rclcpp::ok() when playing back messages (#54 <https://github.com/ros2/rosbag2/issues/54>)
* Extract recorder from rosbag2_transport, fix test naming (#44 <https://github.com/ros2/rosbag2/issues/44>)
* Introduce rosbag2_transport layer and CLI (#38 <https://github.com/ros2/rosbag2/issues/38>)
* Contributors: Alessandro Bottero, Andreas Greimel, Andreas Holzner, Karsten Knese, Martin Idel
```

## shared_queues_vendor

```
* Add correct timing behaviour for rosbag play (#32 <https://github.com/ros2/rosbag2/issues/32>)
* Contributors: Martin Idel
```

## sqlite3_vendor

```
* add sqlite3 vendor package for cross-platform capabilities (#5 <https://github.com/ros2/rosbag2/issues/5>)
* Contributors: Karsten Knese
```

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Do you want to enable PR testing for that repo?

**Comment by Karsten1987** [comment]
I decided not to given that I don't know yet how the build farm will react on these packages. Is it generally recommended to enable?

**Comment by nuclearsandwich** [comment]
> I decided not to given that I don't know yet how the build farm will react on these packages. Is it generally recommended to enable?

Especially for packages in the ros2 org which definitely has permission for the webhook to set I don't think it can hurt to try. From offline conversations it sounds like there's CI running on rosbag2 that requires a more complex environment, but if there's a default subset of tests that can be run with just ROS2 packages, then having PR jobs will give very fast (relative to full ROS2 CI builds) feedback which might help catch things before a full CI run is triggered. I'd say enable them and if there are issues we can decide to disable them.

**Comment by dirk-thomas** [comment]
@Karsten1987 If this PR was superseded by #455 please close it.

**Pull request closed without merging**
